name: Xcode - Build and Analyze
on:
  workflow_dispatch:
jobs:
  build:
    name: CI/CD
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Install
        run: |
          curl -o package.json -L https://raw.githubusercontent.com/juspay/hyperswitch-client-core/main/package.json
          yarn
          cd frameworkgen
          brew bundle install --no-lock --file Brewfile
          bundle install
          xcodegen && RCT_NEW_ARCH_ENABLED=0 USE_FRAMEWORKS=dynamic bundle exec pod install --verbose && scripts/xcode_env.sh
      - name: Framework Generation
        run: |
          cd frameworkgen
          scripts/archive.sh iphoneos && scripts/archive.sh iphonesimulator && scripts/framework.sh
      - name: Create Release
        env:
          CI_COMMIT_MESSAGE: Continuous Integration
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          rm -rf package.json yarn.lock frameworkgen/PrivacyInfo.xcprivacy
          git config --global user.email "${{env.USER_EMAIL}}"
          git config --global user.name "${{env.USER_NAME}}"
          git add -A
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          VERSION=$(grep -E '^version = "(.+)"$' hyperswitch-sdk-ios.podspec | sed 's/^version = "\(.*\)"$/\1/')
          git tag "v$VERSION"
          git push --tags
      - name: Cocoapods Lint & Upload
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod spec lint --allow-warnings
          pod trunk push hyperswitch-sdk-ios.podspec --allow-warnings
